apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: calculator
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: 633321192470.dkr.ecr.us-east-1.amazonaws.com/calculator:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
